FROM mhart/alpine-node:10.4.1

ARG ANGULAR_WORKDIR
WORKDIR $ANGULAR_WORKDIR
COPY package*.json $ANGULAR_WORKDIR/

# Need build dependencies
RUN npm install --development

COPY ./*.json $ANGULAR_WORKDIR/
COPY ./src $ANGULAR_WORKDIR/src

CMD npx ng serve --host 0.0.0.0 --port $ANGULAR_PORT
