npx postgraphile \
  -n 0.0.0.0 \
  -p $API_PORT \
  --cors \
  --show-error-stack \
  --extended-errors hint,detail,errcode \
  -c postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB \
  --default-role forum_example_anonymous \
  --jwt-token-identifier forum_example.jwt_token \
  --jwt-secret abcd \
  --schema forum_example \
  --watch
